router_ip: "192.168.1.1"   
interface: "eth0"                        
ping_duration: 10                        
download_url: "http://speedtest.tele2.net/10MB.zip"   
download_timeout: 60                     
video_ids:                               
  - dQw4w9WgXcQ   
  - M7FIvfx5J10   
  - 3JZ_D3ELwOQ   
  - L_jWHffIx5E   
  - kJQP7kiw5Fk   
video_duration: 45                       
